# Generated by Django 3.2.6 on 2021-08-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_rename_model_phone_phone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
