# Generated by Django 3.2.6 on 2021-08-08 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_phone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='contact_number',
            field=models.CharField(default=359886338688, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
