# Generated by Django 3.2.6 on 2021-08-08 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_phone_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='contact_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
