# Generated by Django 3.2.6 on 2021-08-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_alter_phone_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='memory',
            field=models.PositiveIntegerField(default=256),
            preserve_default=False,
        ),
    ]
