# Generated by Django 3.2.6 on 2021-08-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.PositiveIntegerField(choices=[(16, 16), (32, 32), (64, 64), (128, 128), (256, 256), (512, 512)]),
        ),
    ]
